version: '2.1'

services:
  geoguess:
    build: .
    # image:
    environment:
      # Set these environment variables when running locally
      # Copy the values from your .env file or set them directly
      #- VUE_APP_PUBLIC_PATH=/
      - VUE_APP_API_KEY=${VUE_APP_API_KEY:-}
      #- VUE_APP_FIREBASE_API_KEY=${VUE_APP_FIREBASE_API_KEY:-}
      #- VUE_APP_FIREBASE_PROJECT_ID=${VUE_APP_FIREBASE_PROJECT_ID:-}
      #- VUE_APP_FIREBASE_MESSAGING_SENDER_ID=${VUE_APP_FIREBASE_MESSAGING_SENDER_ID:-}
      #- VUE_APP_FIREBASE_APP_ID=${VUE_APP_FIREBASE_APP_ID:-}
      #- VUE_APP_FIREBASE_MEASUREMENT_ID=${VUE_APP_FIREBASE_MEASUREMENT_ID:-}
      #- VUE_APP_FIREBASE_AUTH_DOMAIN=${VUE_APP_FIREBASE_AUTH_DOMAIN:-}
      #- VUE_APP_FIREBASE_DATABASE_URL=${VUE_APP_FIREBASE_DATABASE_URL:-}
      #- VUE_APP_STORAGE_BUCKET=${VUE_APP_STORAGE_BUCKET:-}
    ports:
      - 3000:80
